title: Site


columns: 
  - width: 2/3
    sections:
      notes:
        headline: Notes
        type: pages
        parent: site.find("notes")
        template: note
        status: all
        empty: No note yet
        sortBy: date desc
        limit: 3
      links:
        headline: Links
        type: pages
        parent: site.find("links")
        template: link
        status: all
        empty: No link yet
        sortBy: date desc
        limit: 3
      websites:
        headline: Websites
        type: pages
        parent: site.find("websites")
        template: website
        status: all
        empty: No website yet
        sortBy: date desc
        limit: 3
      interviews:
        headline: Interviews
        type: pages
        parent: site.find("interviews")
        template: interview
        status: all
        empty: No interview yet
        sortBy: date desc
        limit: 3
      quotes:
        headline: Quotes
        type: pages
        parent: site.find("quotes")
        template: quote
        status: all
        empty: No quote yet
        sortBy: date desc
        limit: 3
      commentions:
        type: commentions
        show: pending

  - width: 1/3
    sections:
      pages:
        headline: Pages
        type: pages
        sortable: false
        templates:
          - home
          - notes
          - links
          - themes
          - about
          - interviews
          - quotes
          - timeline